### ISSUE TITLE
Unable to understand

### ISSUE THREAD

**Issue by wangzhenhui1992** [mbadry1/DeepLearning.ai-Summary#24]
[GloVe word vectors](https://github.com/mbadry1/DeepLearning.ai-Summary/tree/master/5-%20Sequence%20Models#glove-word-vectors)
> For stop words like this, is, the it gives it a low weight, also for words that doesn't occur so much.
It's too difficult to understand and I don't know the meaning.
And I think it should be fixed with correct grammar.

**Comment by mbadry1** [comment]
Instead of:

- f(x) is given to help with the log 0 problem. Also it gives weights for some words. For stop words like this, is, the it gives it a low weight, also for words that doesn't occur so much.

What about this:

- f(x) -the weighting term- is used for many reasons which includes:
  - The log(0) problem, which might occur if there are no pairs for the given target and context values.
  - Giving low weights for stop words like "is", "the", and "this" because they occurs a lot.
  - Giving low weights for words that doesn't occur so much.

**Comment by mbadry1** [comment]
Done,
